/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Blank2574 (https://sketchfab.com/Blank2574)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/small-space-ship-low-poly-4e852173138b4a7aa8379bb77eecec39
title: Small space ship-low poly
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pCylinder13_lambert2_0: THREE.Mesh
  }
  materials: {
    lambert2: THREE.MeshStandardMaterial
  }
}

export default function Model({ position, ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('./frontend/models/spaceship/scene.gltf') as GLTFResult

  return (
    <group ref={group} scale={3} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder13_lambert2_0.geometry}
            material={materials.lambert2}
            position={position}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./frontend/models/spaceship/scene.gltf')
